# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 20:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multi_email_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organo', models.CharField(max_length=255)),
                ('nombre_original', models.CharField(max_length=1500)),
                ('nombre_admin', models.CharField(blank=True, max_length=1500, null=True)),
                ('comentarios', models.TextField(blank=True, default='')),
                ('comentarios_admin', models.TextField(blank=True, default='')),
                ('tipo_punto', models.CharField(choices=[(b'INFO', b'Informaci\xc3\xb3n'), (b'APRO', b'Aprobaci\xc3\xb3n por Consejo de Direcci\xc3\xb3n'), (b'DSA', b'Deliberaci\xc3\xb3n sin aprobaci\xc3\xb3n por Consejo de Direcci\xc3\xb3n'), (b'DCA', b'Deliberaci\xc3\xb3n con aprobaci\xc3\xb3n por Consejo de Direcci\xc3\xb3n')], default=b'INFO', max_length=4)),
                ('requiere_elevacion', models.BooleanField(default=False)),
                ('duracion_estimada', models.DurationField(default=datetime.timedelta(0, 1200))),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado_punto', models.CharField(choices=[(b'INPO', b'Informado positivamente'), (b'ACD', b'Aprobado por Consejo de Direcci\xc3\xb3n'), (b'DEL', b'Deliberado'), (b'ST', b'Sin tratar'), (b'TRAS', b'Trasladado a otro Consejo'), (b'RECH', b'Rechazado'), (b'CONV', b'Convocado')], default=b'ST', max_length=4)),
                ('estado_punto_anterior', models.CharField(blank=True, choices=[(b'INPO', b'Informado positivamente'), (b'ACD', b'Aprobado por Consejo de Direcci\xc3\xb3n'), (b'DEL', b'Deliberado'), (b'ST', b'Sin tratar'), (b'TRAS', b'Trasladado a otro Consejo'), (b'RECH', b'Rechazado'), (b'CONV', b'Convocado')], max_length=4)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('invitados', multi_email_field.fields.MultiEmailField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('consensuado_con', models.TextField(blank=True, null=True)),
                ('seguimiento', models.TextField(blank=True, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('lugar', models.CharField(max_length=300)),
                ('organo', models.CharField(max_length=255)),
                ('duracion_estimada', models.DurationField(blank=True, null=True)),
                ('estado_reunion', models.CharField(choices=[(b'CRE', b'Creada'), (b'CONV', b'Convocada'), (b'CELE', b'Celebrada')], default=b'CRE', max_length=4)),
                ('asistentes', models.TextField(blank=True, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('puntos', models.ManyToManyField(related_name='puntos_set', to='main.Punto')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='punto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Punto'),
        ),
        migrations.AddField(
            model_name='orden',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reunion'),
        ),
    ]
