# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160512_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos',
            old_name='documentos',
            new_name='documento',
        ),
    ]
