# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160512_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y%m%d%H%M%S'),
        ),
    ]
