# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-03 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reunion_puntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='punto',
            name='invitados',
        ),
        migrations.AlterField(
            model_name='punto',
            name='estado_punto',
            field=models.CharField(choices=[(b'INPO', b'Informado positivamente'), (b'ACD', b'Aprobado por Consejo de Direcci\xc3\xb3n'), (b'DEL', b'Deliberado'), (b'ST', b'Sin tratar'), (b'TRAS', b'Trasladado a otro Consejo'), (b'RECH', b'Rechazado'), (b'CONV', b'Convocado'), (b'ADD', b'A\xc3\xb1adido a una reuni\xc3\xb3n')], default=b'ST', max_length=4),
        ),
        migrations.AlterField(
            model_name='punto',
            name='estado_punto_anterior',
            field=models.CharField(blank=True, choices=[(b'INPO', b'Informado positivamente'), (b'ACD', b'Aprobado por Consejo de Direcci\xc3\xb3n'), (b'DEL', b'Deliberado'), (b'ST', b'Sin tratar'), (b'TRAS', b'Trasladado a otro Consejo'), (b'RECH', b'Rechazado'), (b'CONV', b'Convocado'), (b'ADD', b'A\xc3\xb1adido a una reuni\xc3\xb3n')], max_length=4),
        ),
    ]
